### ISSUE TITLE
EncoderNamedPreset.ContentAwareEncoding

### ISSUE THREAD

**Issue by jasonrelode** [xpouyat/MK.IO#37]
Is there not a present for EncoderNamedPreset.ContentAwareEncoding? We were using that preset.

**Comment by xpouyat** [comment]
MediaKind added CVQ presets recently. I am planning to release a new version of the SDK with these 3 new presets.
https://docs.io.mediakind.com/docs/feb-2024-constant-video-quality-presets

**Comment by xpouyat** [comment]
CVQ in v1.2.0
https://www.nuget.org/packages/MK.IO/1.2.0

**Comment by xpouyat** [comment]
@jasonrelode

**Comment by epicstar** [comment]
> CVQ in v1.2.0 https://www.nuget.org/packages/MK.IO/1.2.0

I was wondering when MediaKind will have CVQ presets for H.265?

Our use-case is playing streamed videos over Brightsigns. Some Brightsigns for 4K require H.265 and won't support H.264: https://support.brightsign.biz/hc/en-us/articles/218065137-Supported-video-formats-and-codecs

I guess you don't have control over that though since you're just the maintainer of the .NET lib.

**Comment by xpouyat** [comment]
Hello,
I am asking the question to MediaKind.

**Comment by xpouyat** [comment]
Hello @epicstar 
MediaKind recommends to open a support ticket so they can track the ask. https://support.mk.io/portal/myarea
