### ISSUE TITLE
Cannot retrieve SAS token

### ISSUE THREAD

**Issue by jasonk-ma** [xpouyat/MK.IO#55]
I'm trying to construct a SAS URI to use in a BlobContainerClient instance:

```
            var storages = _mediaKindClient.StorageAccounts.List();
            var credentials = _mediaKindClient.StorageAccounts.ListCredentials(
                (Guid)storages.First().Metadata.Id
            );
            var credential = _mediaKindClient.StorageAccounts.GetCredential(
                (Guid)storages.First().Metadata.Id,
                (Guid)credentials.First().Metadata.Id
            );

            string storageAccountUrl = $"https://{_storageAccountName}.blob.core.windows.net";
            string containerName = data.DestinationContainer;
            string sasToken = credential.Spec.AzureCredential.SasToken;

            string sasUriString = $"{storageAccountUrl}/{containerName}/{sasToken}";
            BlobContainerClient destinationBlobContainer = new BlobContainerClient(sasUri);
```
            
In this case, the SasToken is null and the blob container lacks the proper auth, but I do see a value in the SasTokenSanitized (with the redacted portion). Why is SasToken NULL but SasTokenSanitized not?

What is the pattern with this MK.IO library to use to achieve the goal here of having a SAS URI constructed?

I also noticed that the library has no way to retrieve the MK.IO Storage Account name and URL which would also be super useful in constructing such URIs.

**Comment by xpouyat** [comment]
Hello,
The .GetCredential() method will only return a sanitized SAS token. This is not an issue with the SDK. This is a by design feature of the MK.IO REST API : https://docs.mk.io/reference/get_apiaccountscustomer_idsubscriptionssubscription_idstoragestorage_idcredentialstoken_id

SasToken is present (as NULL) because this property is used by storage credential create method.

You can retrieve the MK.IO storage account name using
storages.First().Spec.Name

and storage Url using
storages.First().Spec.AzureStorageConfiguration.Url

I hope it helps.
